	.text
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	la	$t3,thingy
	la	$t4,thingy
	la	$t5,thingy
	la	$t0,thingy
	la	$t1,thingy
	la	$t2,thingy
	la	$s0,thingy
	la	$s1,thingy
	la	$s2,thingy
	la	$s3,thingy
	.data
thingy:	.word	12	
